//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.454
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsanie.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsanie.UI.Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Av号或者Vid为空！ 的本地化字符串。
        /// </summary>
        internal static string AvVidEmpty {
            get {
                return ResourceManager.GetString("AvVidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string buttonClose {
            get {
                return ResourceManager.GetString("buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登录 的本地化字符串。
        /// </summary>
        internal static string checkAutoLogin {
            get {
                return ResourceManager.GetString("checkAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查登录 的本地化字符串。
        /// </summary>
        internal static string CheckLogin {
            get {
                return ResourceManager.GetString("CheckLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在通信... 的本地化字符串。
        /// </summary>
        internal static string Communicating {
            get {
                return ResourceManager.GetString("Communicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string datacolColor {
            get {
                return ResourceManager.GetString("datacolColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        internal static string datacolFontsize {
            get {
                return ResourceManager.GetString("datacolFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 的本地化字符串。
        /// </summary>
        internal static string datacolMode {
            get {
                return ResourceManager.GetString("datacolMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string datacolPlayTime {
            get {
                return ResourceManager.GetString("datacolPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕内容 的本地化字符串。
        /// </summary>
        internal static string datacolText {
            get {
                return ResourceManager.GetString("datacolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪。 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载弹幕 的本地化字符串。
        /// </summary>
        internal static string DownloadDanmaku {
            get {
                return ResourceManager.GetString("DownloadDanmaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在通过 vid: {0} 下载弹幕... 的本地化字符串。
        /// </summary>
        internal static string DownloadDanmakuStatus {
            get {
                return ResourceManager.GetString("DownloadDanmakuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载成功！一共 {0} 条弹幕。 的本地化字符串。
        /// </summary>
        internal static string DownloadDanmakuSucceed {
            get {
                return ResourceManager.GetString("DownloadDanmakuSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败... 的本地化字符串。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SimSun 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 134 的本地化字符串。
        /// </summary>
        internal static string GdiCharSet {
            get {
                return ResourceManager.GetString("GdiCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取验证码 的本地化字符串。
        /// </summary>
        internal static string GetValidCode {
            get {
                return ResourceManager.GetString("GetValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 Vid 的本地化字符串。
        /// </summary>
        internal static string GetVidOfAv {
            get {
                return ResourceManager.GetString("GetVidOfAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取 av: {0} 的 vid... 的本地化字符串。
        /// </summary>
        internal static string GetVidOfAvStatus {
            get {
                return ResourceManager.GetString("GetVidOfAvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游客 的本地化字符串。
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作已中断。 的本地化字符串。
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码: 的本地化字符串。
        /// </summary>
        internal static string labelValidCode {
            get {
                return ResourceManager.GetString("labelValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuEditAdd {
            get {
                return ResourceManager.GetString("menuEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string menuEditCopy {
            get {
                return ResourceManager.GetString("menuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切割(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuEditCutting {
            get {
                return ResourceManager.GetString("menuEditCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除弹幕(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string menuEditDelete {
            get {
                return ResourceManager.GetString("menuEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string menuEditEdit {
            get {
                return ResourceManager.GetString("menuEditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入(&amp;I) 的本地化字符串。
        /// </summary>
        internal static string menuEditInsert {
            get {
                return ResourceManager.GetString("menuEditInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuEditMoveDown {
            get {
                return ResourceManager.GetString("menuEditMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string menuEditMoveUp {
            get {
                return ResourceManager.GetString("menuEditMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string menuEditPaste {
            get {
                return ResourceManager.GetString("menuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(&amp;H) 的本地化字符串。
        /// </summary>
        internal static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string menuMultiple {
            get {
                return ResourceManager.GetString("menuMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在弹幕后添加(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleAppendAfter {
            get {
                return ResourceManager.GetString("menuMultipleAppendAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColor {
            get {
                return ResourceManager.GetString("menuMultipleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改到... 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColorConstant {
            get {
                return ResourceManager.GetString("menuMultipleColorConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渐变修改... 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColorGradient {
            get {
                return ResourceManager.GetString("menuMultipleColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleFontsize {
            get {
                return ResourceManager.GetString("menuMultipleFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在弹幕前插入(&amp;I) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleInsertBefore {
            get {
                return ResourceManager.GetString("menuMultipleInsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕模式(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleMode {
            get {
                return ResourceManager.GetString("menuMultipleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode7 弹幕(&amp;7) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleMode7 {
            get {
                return ResourceManager.GetString("menuMultipleMode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现时间(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTime {
            get {
                return ResourceManager.GetString("menuMultiplePlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改到... 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTimeConstant {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增量... 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTimeIncrease {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuOperation {
            get {
                return ResourceManager.GetString("menuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string menuOperationDownload {
            get {
                return ResourceManager.GetString("menuOperationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(&amp;X) 的本地化字符串。
        /// </summary>
        internal static string menuOperationExit {
            get {
                return ResourceManager.GetString("menuOperationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string menuOperationLogin {
            get {
                return ResourceManager.GetString("menuOperationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuOperationOpen {
            get {
                return ResourceManager.GetString("menuOperationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string menuOperationSave {
            get {
                return ResourceManager.GetString("menuOperationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string menuOperationSaveAs {
            get {
                return ResourceManager.GetString("menuOperationSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string menuOperationUpload {
            get {
                return ResourceManager.GetString("menuOperationUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuToolsOption {
            get {
                return ResourceManager.GetString("menuToolsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开播放器(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string menuToolsPlayer {
            get {
                return ResourceManager.GetString("menuToolsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未实现 的本地化字符串。
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点我重新获取验证码 的本地化字符串。
        /// </summary>
        internal static string pictureValidCode_ToolTipText {
            get {
                return ResourceManager.GetString("pictureValidCode_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕字号属性值无效。 的本地化字符串。
        /// </summary>
        internal static string PropertyInvalidFontsize {
            get {
                return ResourceManager.GetString("PropertyInvalidFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放时间属性值无效。 的本地化字符串。
        /// </summary>
        internal static string PropertyInvalidPlayTime {
            get {
                return ResourceManager.GetString("PropertyInvalidPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕池属性值无效。 的本地化字符串。
        /// </summary>
        internal static string PropertyInvalidPool {
            get {
                return ResourceManager.GetString("PropertyInvalidPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性值不可为 null。 的本地化字符串。
        /// </summary>
        internal static string PropertyNull {
            get {
                return ResourceManager.GetString("PropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态不成功 的本地化字符串。
        /// </summary>
        internal static string StatusNotOK {
            get {
                return ResourceManager.GetString("StatusNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功！ 的本地化字符串。
        /// </summary>
        internal static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string textPassword {
            get {
                return ResourceManager.GetString("textPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string textUser {
            get {
                return ResourceManager.GetString("textUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string textValidCode {
            get {
                return ResourceManager.GetString("textValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新弹幕... 的本地化字符串。
        /// </summary>
        internal static string toolButtonAdd {
            get {
                return ResourceManager.GetString("toolButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载弹幕 的本地化字符串。
        /// </summary>
        internal static string toolButtonDownload {
            get {
                return ResourceManager.GetString("toolButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开弹幕文件 的本地化字符串。
        /// </summary>
        internal static string toolButtonOpen {
            get {
                return ResourceManager.GetString("toolButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开播放器 的本地化字符串。
        /// </summary>
        internal static string toolButtonPlayer {
            get {
                return ResourceManager.GetString("toolButtonPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string toolButtonPost {
            get {
                return ResourceManager.GetString("toolButtonPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送弹幕 的本地化字符串。
        /// </summary>
        internal static string toolButtonPost_ToolTipText {
            get {
                return ResourceManager.GetString("toolButtonPost_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存弹幕文件 的本地化字符串。
        /// </summary>
        internal static string toolButtonSave {
            get {
                return ResourceManager.GetString("toolButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择发送人弹幕 的本地化字符串。
        /// </summary>
        internal static string toolButtonSelect {
            get {
                return ResourceManager.GetString("toolButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止 的本地化字符串。
        /// </summary>
        internal static string toolButtonStop {
            get {
                return ResourceManager.GetString("toolButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传xml弹幕 的本地化字符串。
        /// </summary>
        internal static string toolButtonUpload {
            get {
                return ResourceManager.GetString("toolButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未命名 的本地化字符串。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NSimSun 的本地化字符串。
        /// </summary>
        internal static string WidthFontName {
            get {
                return ResourceManager.GetString("WidthFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8.75 的本地化字符串。
        /// </summary>
        internal static string WidthFontSize {
            get {
                return ResourceManager.GetString("WidthFontSize", resourceCulture);
            }
        }
    }
}
