//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.454
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsanie.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsanie.UI.Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Segoe UI 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 134 的本地化字符串。
        /// </summary>
        internal static string GdiCharSet {
            get {
                return ResourceManager.GetString("GdiCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuEditAdd {
            get {
                return ResourceManager.GetString("menuEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string menuEditCopy {
            get {
                return ResourceManager.GetString("menuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切割(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuEditCutting {
            get {
                return ResourceManager.GetString("menuEditCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除弹幕(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string menuEditDelete {
            get {
                return ResourceManager.GetString("menuEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string menuEditEdit {
            get {
                return ResourceManager.GetString("menuEditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入(&amp;I) 的本地化字符串。
        /// </summary>
        internal static string menuEditInsert {
            get {
                return ResourceManager.GetString("menuEditInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuEditMoveDown {
            get {
                return ResourceManager.GetString("menuEditMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string menuEditMoveUp {
            get {
                return ResourceManager.GetString("menuEditMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string menuEditPaste {
            get {
                return ResourceManager.GetString("menuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(&amp;H) 的本地化字符串。
        /// </summary>
        internal static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string menuMultiple {
            get {
                return ResourceManager.GetString("menuMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在弹幕后添加(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleAppendAfter {
            get {
                return ResourceManager.GetString("menuMultipleAppendAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColor {
            get {
                return ResourceManager.GetString("menuMultipleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改到... 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColorConstant {
            get {
                return ResourceManager.GetString("menuMultipleColorConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渐变修改... 的本地化字符串。
        /// </summary>
        internal static string menuMultipleColorGradient {
            get {
                return ResourceManager.GetString("menuMultipleColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleFontsize {
            get {
                return ResourceManager.GetString("menuMultipleFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在弹幕前插入(&amp;I) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleInsertBefore {
            get {
                return ResourceManager.GetString("menuMultipleInsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕模式(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleMode {
            get {
                return ResourceManager.GetString("menuMultipleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode7 弹幕(&amp;7) 的本地化字符串。
        /// </summary>
        internal static string menuMultipleMode7 {
            get {
                return ResourceManager.GetString("menuMultipleMode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现时间(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTime {
            get {
                return ResourceManager.GetString("menuMultiplePlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改到... 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTimeConstant {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增量... 的本地化字符串。
        /// </summary>
        internal static string menuMultiplePlayTimeIncrease {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuOperation {
            get {
                return ResourceManager.GetString("menuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string menuOperationDownload {
            get {
                return ResourceManager.GetString("menuOperationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(&amp;X) 的本地化字符串。
        /// </summary>
        internal static string menuOperationExit {
            get {
                return ResourceManager.GetString("menuOperationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录(&amp;L) 的本地化字符串。
        /// </summary>
        internal static string menuOperationLogin {
            get {
                return ResourceManager.GetString("menuOperationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuOperationOpen {
            get {
                return ResourceManager.GetString("menuOperationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string menuOperationSave {
            get {
                return ResourceManager.GetString("menuOperationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string menuOperationSaveAs {
            get {
                return ResourceManager.GetString("menuOperationSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传(&amp;U) 的本地化字符串。
        /// </summary>
        internal static string menuOperationUpload {
            get {
                return ResourceManager.GetString("menuOperationUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具(&amp;T) 的本地化字符串。
        /// </summary>
        internal static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string menuToolsOption {
            get {
                return ResourceManager.GetString("menuToolsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开播放器(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string menuToolsPlayer {
            get {
                return ResourceManager.GetString("menuToolsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolas 的本地化字符串。
        /// </summary>
        internal static string WidthFontName {
            get {
                return ResourceManager.GetString("WidthFontName", resourceCulture);
            }
        }
    }
}
