//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsanie.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsanie.UI.Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av号或者Vid为空！.
        /// </summary>
        internal static string AvVidEmpty {
            get {
                return ResourceManager.GetString("AvVidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭(&amp;C).
        /// </summary>
        internal static string buttonClose {
            get {
                return ResourceManager.GetString("buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录(&amp;L).
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动登录.
        /// </summary>
        internal static string checkAutoLogin {
            get {
                return ResourceManager.GetString("checkAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查登录.
        /// </summary>
        internal static string CheckLogin {
            get {
                return ResourceManager.GetString("CheckLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在通信....
        /// </summary>
        internal static string Communicating {
            get {
                return ResourceManager.GetString("Communicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        internal static string datacolColor {
            get {
                return ResourceManager.GetString("datacolColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字号.
        /// </summary>
        internal static string datacolFontsize {
            get {
                return ResourceManager.GetString("datacolFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式.
        /// </summary>
        internal static string datacolMode {
            get {
                return ResourceManager.GetString("datacolMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string datacolPlayTime {
            get {
                return ResourceManager.GetString("datacolPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕内容.
        /// </summary>
        internal static string datacolText {
            get {
                return ResourceManager.GetString("datacolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪。.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载弹幕.
        /// </summary>
        internal static string DownloadDanmaku {
            get {
                return ResourceManager.GetString("DownloadDanmaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在通过 vid: {0} 下载弹幕....
        /// </summary>
        internal static string DownloadDanmakuStatus {
            get {
                return ResourceManager.GetString("DownloadDanmakuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载成功！一共 {0} 条弹幕。.
        /// </summary>
        internal static string DownloadDanmakuSucceed {
            get {
                return ResourceManager.GetString("DownloadDanmakuSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败....
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimSun.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 134.
        /// </summary>
        internal static string GdiCharSet {
            get {
                return ResourceManager.GetString("GdiCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取验证码.
        /// </summary>
        internal static string GetValidCode {
            get {
                return ResourceManager.GetString("GetValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取 Vid.
        /// </summary>
        internal static string GetVidOfAv {
            get {
                return ResourceManager.GetString("GetVidOfAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在获取 av: {0} 的 vid....
        /// </summary>
        internal static string GetVidOfAvStatus {
            get {
                return ResourceManager.GetString("GetVidOfAvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游客.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作已中断。.
        /// </summary>
        internal static string Interrupt {
            get {
                return ResourceManager.GetString("Interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名:.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码:.
        /// </summary>
        internal static string labelValidCode {
            get {
                return ResourceManager.GetString("labelValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑(&amp;E).
        /// </summary>
        internal static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加(&amp;A).
        /// </summary>
        internal static string menuEditAdd {
            get {
                return ResourceManager.GetString("menuEditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制(&amp;C).
        /// </summary>
        internal static string menuEditCopy {
            get {
                return ResourceManager.GetString("menuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切割(&amp;T).
        /// </summary>
        internal static string menuEditCutting {
            get {
                return ResourceManager.GetString("menuEditCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除弹幕(&amp;D).
        /// </summary>
        internal static string menuEditDelete {
            get {
                return ResourceManager.GetString("menuEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑(&amp;E).
        /// </summary>
        internal static string menuEditEdit {
            get {
                return ResourceManager.GetString("menuEditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入(&amp;I).
        /// </summary>
        internal static string menuEditInsert {
            get {
                return ResourceManager.GetString("menuEditInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下移(&amp;O).
        /// </summary>
        internal static string menuEditMoveDown {
            get {
                return ResourceManager.GetString("menuEditMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上移(&amp;U).
        /// </summary>
        internal static string menuEditMoveUp {
            get {
                return ResourceManager.GetString("menuEditMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴(&amp;P).
        /// </summary>
        internal static string menuEditPaste {
            get {
                return ResourceManager.GetString("menuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助(&amp;H).
        /// </summary>
        internal static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于(&amp;A).
        /// </summary>
        internal static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量(&amp;M).
        /// </summary>
        internal static string menuMultiple {
            get {
                return ResourceManager.GetString("menuMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在弹幕后添加(&amp;A).
        /// </summary>
        internal static string menuMultipleAppendAfter {
            get {
                return ResourceManager.GetString("menuMultipleAppendAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色(&amp;C).
        /// </summary>
        internal static string menuMultipleColor {
            get {
                return ResourceManager.GetString("menuMultipleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改到....
        /// </summary>
        internal static string menuMultipleColorConstant {
            get {
                return ResourceManager.GetString("menuMultipleColorConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渐变修改....
        /// </summary>
        internal static string menuMultipleColorGradient {
            get {
                return ResourceManager.GetString("menuMultipleColorGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小(&amp;S).
        /// </summary>
        internal static string menuMultipleFontsize {
            get {
                return ResourceManager.GetString("menuMultipleFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在弹幕前插入(&amp;I).
        /// </summary>
        internal static string menuMultipleInsertBefore {
            get {
                return ResourceManager.GetString("menuMultipleInsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕模式(&amp;M).
        /// </summary>
        internal static string menuMultipleMode {
            get {
                return ResourceManager.GetString("menuMultipleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode7 弹幕(&amp;7).
        /// </summary>
        internal static string menuMultipleMode7 {
            get {
                return ResourceManager.GetString("menuMultipleMode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出现时间(&amp;T).
        /// </summary>
        internal static string menuMultiplePlayTime {
            get {
                return ResourceManager.GetString("menuMultiplePlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改到....
        /// </summary>
        internal static string menuMultiplePlayTimeConstant {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增量....
        /// </summary>
        internal static string menuMultiplePlayTimeIncrease {
            get {
                return ResourceManager.GetString("menuMultiplePlayTimeIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作(&amp;O).
        /// </summary>
        internal static string menuOperation {
            get {
                return ResourceManager.GetString("menuOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载(&amp;D).
        /// </summary>
        internal static string menuOperationDownload {
            get {
                return ResourceManager.GetString("menuOperationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出(&amp;X).
        /// </summary>
        internal static string menuOperationExit {
            get {
                return ResourceManager.GetString("menuOperationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录(&amp;L).
        /// </summary>
        internal static string menuOperationLogin {
            get {
                return ResourceManager.GetString("menuOperationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开(&amp;O).
        /// </summary>
        internal static string menuOperationOpen {
            get {
                return ResourceManager.GetString("menuOperationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存(&amp;S).
        /// </summary>
        internal static string menuOperationSave {
            get {
                return ResourceManager.GetString("menuOperationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为(&amp;A)....
        /// </summary>
        internal static string menuOperationSaveAs {
            get {
                return ResourceManager.GetString("menuOperationSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传(&amp;U).
        /// </summary>
        internal static string menuOperationUpload {
            get {
                return ResourceManager.GetString("menuOperationUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具(&amp;T).
        /// </summary>
        internal static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项(&amp;O).
        /// </summary>
        internal static string menuToolsOption {
            get {
                return ResourceManager.GetString("menuToolsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开播放器(&amp;P).
        /// </summary>
        internal static string menuToolsPlayer {
            get {
                return ResourceManager.GetString("menuToolsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未实现.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点我重新获取验证码.
        /// </summary>
        internal static string pictureValidCode_ToolTipText {
            get {
                return ResourceManager.GetString("pictureValidCode_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕字号属性值无效。.
        /// </summary>
        internal static string PropertyInvalidFontsize {
            get {
                return ResourceManager.GetString("PropertyInvalidFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放时间属性值无效。.
        /// </summary>
        internal static string PropertyInvalidPlayTime {
            get {
                return ResourceManager.GetString("PropertyInvalidPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕池属性值无效。.
        /// </summary>
        internal static string PropertyInvalidPool {
            get {
                return ResourceManager.GetString("PropertyInvalidPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性值不可为 null。.
        /// </summary>
        internal static string PropertyNull {
            get {
                return ResourceManager.GetString("PropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接状态不成功.
        /// </summary>
        internal static string StatusNotOK {
            get {
                return ResourceManager.GetString("StatusNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        internal static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string textPassword {
            get {
                return ResourceManager.GetString("textPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string textUser {
            get {
                return ResourceManager.GetString("textUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        internal static string textValidCode {
            get {
                return ResourceManager.GetString("textValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新弹幕....
        /// </summary>
        internal static string toolButtonAdd {
            get {
                return ResourceManager.GetString("toolButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载弹幕.
        /// </summary>
        internal static string toolButtonDownload {
            get {
                return ResourceManager.GetString("toolButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开弹幕文件.
        /// </summary>
        internal static string toolButtonOpen {
            get {
                return ResourceManager.GetString("toolButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开播放器.
        /// </summary>
        internal static string toolButtonPlayer {
            get {
                return ResourceManager.GetString("toolButtonPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        internal static string toolButtonPost {
            get {
                return ResourceManager.GetString("toolButtonPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送弹幕.
        /// </summary>
        internal static string toolButtonPost_ToolTipText {
            get {
                return ResourceManager.GetString("toolButtonPost_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存弹幕文件.
        /// </summary>
        internal static string toolButtonSave {
            get {
                return ResourceManager.GetString("toolButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择发送人弹幕.
        /// </summary>
        internal static string toolButtonSelect {
            get {
                return ResourceManager.GetString("toolButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 终止.
        /// </summary>
        internal static string toolButtonStop {
            get {
                return ResourceManager.GetString("toolButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传xml弹幕.
        /// </summary>
        internal static string toolButtonUpload {
            get {
                return ResourceManager.GetString("toolButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未命名.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSimSun.
        /// </summary>
        internal static string WidthFontName {
            get {
                return ResourceManager.GetString("WidthFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string WidthFontSize {
            get {
                return ResourceManager.GetString("WidthFontSize", resourceCulture);
            }
        }
    }
}
